Repository pointnetwork/pointnetwork, pull requests merged in 2022-03, with the labels that each got.

#229 start hardhat transition
  deployer.Dockerfile
  docker-compose.base.yaml
  docker-compose.dev.yaml
  docker-compose.e2e.yaml
  docker-compose.zappdev.yaml
  docker-compose.znet.local.yaml
  example/blog.z/contracts/Blog.sol
  example/hello.z/contracts/Hello.sol
  example/pointsocial.z/contracts/PointSocial.sol
  example/store.z/contracts/Store.sol
  example/template.z/contracts/Template.sol
  example/twitter.z/contracts/Twitter.sol
  hardhat/.eslintignore
  hardhat/.eslintrc.js
  hardhat/.gitignore
  hardhat/.npmignore
  hardhat/.prettierignore
  hardhat/.solhint.json
  hardhat/.solhintignore
  hardhat/README.md
  hardhat/contracts/Identity.sol
  hardhat/contracts/StorageProviderRegistry.sol
  hardhat/hardhat.config.ts
  hardhat/package-lock.json
  hardhat/package.json
  hardhat/scripts/deploy.ts
  hardhat/tsconfig.json
  package.json
  scripts/deploy-contracts-docker.js
  scripts/run-node.sh
  src/client/zweb/renderer/index.js
  src/core/deploy.js
  src/index.ts
  src/network/web3bridge.js
  src/util/contract.ts
Labels: ready to merge

#244 Adding coverage to contracts for & Remove StorageProviderRegistry
  config/custom-environment-variables.yaml
  config/default.yaml
  example/blog.z/contracts/Blog.sol
  hardhat/.solhint.json
  hardhat/contracts/StorageProviderRegistry.sol
  hardhat/scripts/deploy.ts
  hardhat/test/unit/Identity_test.ts
  hardhat/test/unit/pointSocial.ts
  src/index.ts
  src/network/web3bridge.js
Labels: post hardhat merge

#277 Move proxy server response html templates to separate files
  package-lock.json
  package.json
  src/client/proxy/index.js
  src/client/proxy/templateManager.ts
  src/client/proxy/views/directory.hbs
  src/client/proxy/views/error.hbs
  src/client/proxy/views/redirect.hbs
Labels: ready to merge

#281 Update Jest, remove unused and comment out broken tests
  babel.config.js
  config/test.yaml
  package-lock.json
  package.json
  tests/client/proxy.spec.js
  tests/models/provider.spec.js
  tests/models/provider_chunk.spec.js
  tests/models/redkeys.spec.js
  tests/threads/encryptDecrypt.spec.js
Labels: work in progress

#283 Remove address from logs' tags and add identifier
  package-lock.json
  package.json
  src/core/log.js
  src/util/getIdentifier.ts
Labels: ready to merge, waiting review

#287 Feature/refactor proxy
  .eslintrc.js
  docker-compose.test.yaml
  package-lock.json
  package.json
  tests/client/proxy.spec.js
  tests/core/utils.spec.js
  tests/docker/proxy.spec.js
  tests/docker/storage.spec.js
  tests/email.validation.spec.js
  tests/threads/encryptDecrypt.spec.js
Labels: work in progress
