Repository pointnetwork/pointnetwork, pull requests merged in 2022-10, with the labels that each got.

#733 PN-256 Change Solana RPC provider
  config/development.yaml
  config/devlocal.yaml
  config/gateway.yaml
  config/production.yaml
  config/visitlocal.yaml
Labels: configuration

#734 PN-269 Add feature flags to toggle name services on/off
  config/default.yaml
  src/network/providers/ethereum.js
  src/network/providers/solana.ts
Labels: configuration

#738 PN-273 Allow identities in wallet for token transfers
  internal/explorer.point/src/components/wallet/SendModal.jsx
Labels: enhancement

#740 PN-276 Add address to identity metadata
  src/rpc/decode.ts
Labels: improvement

#739 PN-275 Fix improper string replacements, which led to various bugs
  src/api/controllers/ContractController.js
  src/client/zweb/deployer/index.js
  src/client/zweb/renderer/index.js
  src/network/providers/ethereum.js
Labels: fix

#745 PN-279 Fix linter issues
  internal/explorer.point/.eslintrc.js
  internal/explorer.point/src/components/identity/Deployers.jsx
  internal/explorer.point/src/components/identity/IkvEntry.jsx
  internal/explorer.point/src/components/identity/IkvList.jsx
  internal/explorer.point/src/components/wallet/TokenRow.jsx
  internal/explorer.point/src/components/wallet/WalletRow.jsx
  internal/explorer.point/src/pages/Home.jsx
  internal/explorer.point/src/pages/Identities.jsx
  internal/explorer.point/src/pages/Identity.jsx
  internal/explorer.point/src/pages/Wallet.jsx
  internal/explorer.point/src/pages/Zapps.jsx
  package-lock.json
  package.json
  src/background/scheduler.ts
  src/client/encryptIdentityUtils.js
  src/client/proxy/handlers/encryptedStorage.ts
  src/client/proxy/handlers/pointApi.ts
  src/client/storage/chunk/upload.ts
  src/client/storage/index.ts
  src/db/models/chunk.ts
  src/index.ts
  src/network/deployer/deployProxyImpl.ts
  src/network/deployer/fetchOrDeploy.ts
  src/network/deployer/manifest.ts
  src/network/deployer/simulateDeploy.ts
  src/network/deployer/upgradeProxy.ts
Labels: codestyle

#742 PN-272 Add endpoint to get list of events by dApp
  src/api/api_routes.js
  src/api/controllers/ContractController.js
Labels: feature

#746 PN-281 Remove history button from Wallet; Fix logo column length
  internal/explorer.point/src/components/wallet/WalletRow.jsx
  internal/explorer.point/src/custom.css
  internal/explorer.point/src/pages/Wallet.jsx
Labels: fix

#747 PN-282 Create and update POINT record in separate txs
  .env
  package-lock.json
  package.json
  src/network/providers/solana.ts
Labels: fix
